[package]
name = "elevator"
version = "0.1.0"
authors = ["Sunjay Varma <varma.sunjay@gmail.com>"]

[dependencies]
lazy_static = "0.1.*"
conrod = "0.36.4"
find_folder = "0.3.0"
piston_window = "0.45.0"

